// app/layout.tsx

import type { Metadata } from "next";
import "./globals.css";

import { TooltipProvider } from "@/components/ui/tooltip";
import { ToastContainer } from "@/components/toast-container";
import { AuthProvider } from "@/components/auth-provider";
import { Breadcrumb, BreadcrumbItem, BreadcrumbLink, BreadcrumbList, BreadcrumbPage, BreadcrumbSeparator } from "@/components/ui/breadcrumb" 
import { Separator } from "@/components/ui/separator"
import { SidebarTrigger } from "@/components/ui/sidebar"


export const metadata: Metadata = {
  title: "Sist ElMorro",
  description: "Generated by Next.js",
  icons: {
    icon: "/logoMorroHoriztl.png",
    shortcut: "/logoMorroHoriztl.png",
    apple: "/logoMorroHoriztl.png",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <body>
        <AuthProvider>
          <TooltipProvider>
            {children}
            <ToastContainer />
          </TooltipProvider>
        </AuthProvider>

        <footer>
          <div className="flex items-center justify-center p-4 text-sm text-muted-foreground">
            &copy; {new Date().getFullYear()} Grupo El Morro. Todos los derechos reservados.
          </div>
        </footer>
      </body>
    </html>
  );
}