import type { Metadata } from "next";
import "./globals.css";

import { TooltipProvider } from "@/components/ui/tooltip";
import { ToastContainer } from "@/components/toast-container";
import { AuthProvider } from "@/components/auth-provider";

export const metadata: Metadata = {
  title: "Mi App",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <TooltipProvider>
            {children}
            <ToastContainer />
          </TooltipProvider>
        </AuthProvider>
      </body>
    </html>
  );
}