import { baseUrl } from "./environment";

export const endpoints = {
    AUTH: {
        LOGIN: `${baseUrl}/auth/login`,
        REGISTER: `${baseUrl}/auth/register`,
        SELECT_COMPANY: `${baseUrl}/auth/select-company`,
        GET_MY_PROFILE: `${baseUrl}/auth/profile`,
    },
    USERS: {
        GET_ALL: `${baseUrl}/users`,
        CREATE: `${baseUrl}/users`,
        UPDATE: `${baseUrl}/users`,
        DELETE: `${baseUrl}/users`,
        GET_BY_ID: `${baseUrl}/users`,
    },
    COMPANIES: {
        GET_ALL: `${baseUrl}/companies`,
        CREATE: `${baseUrl}/companies`,
        UPDATE: `${baseUrl}/companies`,
        DELETE: `${baseUrl}/companies`,
        GET_BY_ID: `${baseUrl}/companies`,
    },
    USER_COMPANIES: {
        GET_ALL: `${baseUrl}/user-companies`,
        ASIGN_COMPANY: `${baseUrl}/user-companies`,
    },
    WAREHOUSES: {
        GET_ALL: `${baseUrl}/warehouses`,
        CREATE: `${baseUrl}/warehouses`,
        UPDATE: `${baseUrl}/warehouses`,
        DELETE: `${baseUrl}/warehouses`,
        GET_BY_ID: `${baseUrl}/warehouses`,
    },
    CATEGORIES: {
        GET_ALL: `${baseUrl}/categories`,
        CREATE: `${baseUrl}/categories`,
        UPDATE: `${baseUrl}/categories`,
        DELETE: `${baseUrl}/categories`,
        GET_BY_ID: `${baseUrl}/categories`,
    },
    BRANDS: {
        GET_ALL: `${baseUrl}/brands`,
        CREATE: `${baseUrl}/brands`,
        UPDATE: `${baseUrl}/brands`,
        DELETE: `${baseUrl}/brands`,
        GET_BY_ID: `${baseUrl}/brands`,
    },
    PRODUCTS: {
        GET_ALL: `${baseUrl}/products`,
        CREATE: `${baseUrl}/products`,
        UPDATE: `${baseUrl}/products`,
        DELETE: `${baseUrl}/products`,
        GET_BY_ID: `${baseUrl}/products`,
    },
    PRODUCT_UNIT: {
        GET_ALL: (productId: string) => `${baseUrl}/products/${productId}/units`,
        CREATE: (productId: string) => `${baseUrl}/products/${productId}/units`,
        UPDATE: (productId: string, id: string) => `${baseUrl}/products/${productId}/units/${id}`,
        DELETE: (productId: string, id: string) => `${baseUrl}/products/${productId}/units/${id}`,
        GET_BY_ID: (productId: string, id: string) => `${baseUrl}/products/${productId}/units/${id}`,
    },
    CUSTOMERS: {
        GET_ALL: `${baseUrl}/customers`,
        CREATE: `${baseUrl}/customers`,
        UPDATE: `${baseUrl}/customers`,
        DELETE: `${baseUrl}/customers`,
        GET_BY_ID: `${baseUrl}/customers`,
    },
    SUPPLIERS: {
        GET_ALL: `${baseUrl}/suppliers`,
        CREATE: `${baseUrl}/suppliers`,
        UPDATE: `${baseUrl}/suppliers`,
        DELETE: `${baseUrl}/suppliers`,
        GET_BY_ID: `${baseUrl}/suppliers`,
    },
    SALES: {
        GET_ALL: `${baseUrl}/sales`,
        CREATE: `${baseUrl}/sales`,
        UPDATE: `${baseUrl}/sales`,
        DELETE: `${baseUrl}/sales`,
        GET_BY_ID: `${baseUrl}/sales`,
        COMPLETE: (id: string) => `${baseUrl}/sales/${id}/complete`,
        CANCEL: (id: string) => `${baseUrl}/sales/${id}/cancel`,
    },
    PURCHASES: {
        GET_ALL: `${baseUrl}/purchases`,
        CREATE: `${baseUrl}/purchases`,
        UPDATE: `${baseUrl}/purchases`,
        DELETE: `${baseUrl}/purchases`,
        GET_BY_ID: `${baseUrl}/purchases`,
        COMPLETE: (id: string) => `${baseUrl}/purchases/${id}/complete`,
        CANCEL: (id: string) => `${baseUrl}/purchases/${id}/cancel`,
    },
    CURRENCIES: {
        GET_ALL: `${baseUrl}/currencies`,
        CREATE: `${baseUrl}/currencies`,
        UPDATE: `${baseUrl}/currencies`,
        DELETE: `${baseUrl}/currencies`,
        GET_BY_ID: `${baseUrl}/currencies`,
    },
    PERMISSIONS: {
        BY_USER: (userId: string) => `${baseUrl}/users/${userId}/permissions`,
        ASIGN_PERMISSION_TO_ROLE:(id: string) => `${baseUrl}/roles/${id}/permissions`,
    },
    ROLES: {
        GET_PERMISSIONS: `${baseUrl}/permissions`,
        GET_ALL: `${baseUrl}/roles`,
        CREATE: `${baseUrl}/roles`,
        GET_BY_ID: `${baseUrl}/roles`,
        UPDATE: `${baseUrl}/roles`,
        DELETE: `${baseUrl}/roles`,
        USERS_BY_ROLE: (userId: string) => `${baseUrl}/users/${userId}/roles`,
        GET_ROLE_BY_USER: (userId: string) => `${baseUrl}/users/${userId}/roles`,
        ROLE_DELETE_BY_USER: (userId: string) => `${baseUrl}/users/${userId}/roles`,
    },
    CASHBOX: {
        GET_ALL: `${baseUrl}/cash-sessions`,
        
    },
    ACCOUNTS: {
        GET_ALL: `${baseUrl}/payment-accounts`,
        CREATE: `${baseUrl}/payment-accounts`,
        UPDATE: `${baseUrl}/payment-accounts`,
        DELETE: `${baseUrl}/payment-accounts`,
        GET_BY_ID: `${baseUrl}/payment-accounts`,
    },
    SERIES: {
        GET_ALL: `${baseUrl}/seller-series`,
        CREATE: `${baseUrl}/seller-series`,
        UPDATE: `${baseUrl}/seller-series`,
        DELETE: `${baseUrl}/seller-series`,
        GET_BY_ID: `${baseUrl}/seller-series`,
    },
}